apiVersion: v1
kind: Service
metadata:
  name: activemq
spec:
  ports:
    - name: activemq
      protocol: TCP
      port: 61616
      targetPort: 61616
  selector:
    app: activemq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq
spec:
  replicas: 0
#  selector:
#    matchLabels:
#      app: activemq
  template:
    metadata:
      name: activemq
      labels:
        app: activemq
        tier: mq
        container_name: activemq
        environment: {{ .Values.label.ENVIRONMENT }}
    spec:
      serviceAccountName: {{ .Release.Namespace }}-sa
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: activemq
      - name: fluentd-config
        configMap:
          name: activemq-fluentd-config
      containers:
      - name: activemq
        image: {{required "Image Info is mandatory! Read the Project Documentation to understand what and where to configure." .Values.image.ACTIVEMQ }}
        imagePullPolicy: IfNotPresent
        ports:
        - name: activemq
          containerPort: 61616
        env:
        - name: ACTIVEMQ_MAX_MEM
          {{- if (eq "Small" .Values.resourceUnit.size) }}
          value: {{ .Values.resourceUnit.small.memory.max.ACTIVEMQ | quote }}
          {{- else if (eq "Medium" .Values.resourceUnit.size) }}
          value: {{ .Values.resourceUnit.medium.memory.max.ACTIVEMQ | quote }}
          {{- else if (eq "Large" .Values.resourceUnit.size) }}
          value: {{ .Values.resourceUnit.large.memory.max.ACTIVEMQ | quote }}
          {{- else if (eq "Xlarge" .Values.resourceUnit.size) }}
          value: {{ .Values.resourceUnit.xlarge.memory.max.ACTIVEMQ | quote }}
          {{- end }}
        resources:
          limits:
            {{- if (eq "Small" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.small.memory.max.ACTIVEMQ }}Mi
            cpu: {{ .Values.resourceUnit.small.cpu.max.ACTIVEMQ }}m
            {{- else if (eq "Medium" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.medium.memory.max.ACTIVEMQ }}Mi
            cpu: {{ .Values.resourceUnit.medium.cpu.max.ACTIVEMQ }}m
            {{- else if (eq "Large" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.large.memory.max.ACTIVEMQ }}Mi
            cpu: {{ .Values.resourceUnit.large.cpu.max.ACTIVEMQ }}m
            {{- else if (eq "Xlarge" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.xlarge.memory.max.ACTIVEMQ }}Mi
            cpu: {{ .Values.resourceUnit.xlarge.cpu.max.ACTIVEMQ }}m
            {{- end }}
          requests:
            {{- if (eq "Small" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.small.memory.max.ACTIVEMQ }}Mi
            cpu: {{ .Values.resourceUnit.small.cpu.max.ACTIVEMQ }}m
            {{- else if (eq "Medium" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.medium.memory.max.ACTIVEMQ }}Mi
            cpu: {{ .Values.resourceUnit.medium.cpu.max.ACTIVEMQ }}m
            {{- else if (eq "Large" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.large.memory.max.ACTIVEMQ }}Mi
            cpu: {{ .Values.resourceUnit.large.cpu.max.ACTIVEMQ }}m
            {{- else if (eq "Xlarge" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.xlarge.memory.max.ACTIVEMQ }}Mi
            cpu: {{ .Values.resourceUnit.xlarge.cpu.max.ACTIVEMQ }}m
            {{- end }}
        volumeMounts:
        - mountPath: /apache-activemq/data
          name: data
          subPath: activemq
        - mountPath: /apache-activemq/conf/log4j.properties
          name: data
          subPath: conf/log4j.properties
        - mountPath: /apache-activemq/conf/jetty.xml
          name: data
          subPath: conf/jetty.xml
        - mountPath: /apache-activemq/conf/activemq.xml
          name: data
          subPath: conf/activemq.xml
        - mountPath: /apache-activemq/tmp
          name: data
          subPath: activemq_tmp
        - mountPath: /tmp
          name: data
          subPath: tmp
        securityContext:
          readOnlyRootFilesystem: true
      - name: fluentd
        image: {{ .Values.image.LOGZIO }}
        env:
        - name:  LOGZIO_TOKEN
          value: {{ .Values.logzio.token | quote }}
        - name:  LOGZIO_URL
          value: {{ .Values.logzio.url | quote }}
        - name: CONTAINER_NAME
          value: activemq
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          value: activemq
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            memory: {{ .Values.logzio.memory }}Mi
          requests:
            cpu: {{ .Values.logzio.cpu }}m
            memory: {{ .Values.logzio.memory }}Mi
        volumeMounts:
        - name: fluentd-config
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        - name: data
          mountPath: /apache-activemq/data
          subPath: activemq
      imagePullSecrets:
        - name: container-registry-key
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        fsGroup: 1000
      allowedCapabilities: null
