apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    tier: app
    role: master
spec:
  ports:
    - name: elasticsearch
      protocol: TCP
      port: 9300
      targetPort: 9300
  selector:
    app: elasticsearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 0
  selector:
    matchLabels:
      app: elasticsearch
      tier: app
      role: master
  template:
    metadata:
      name: elasticsearch
      labels:
        app: elasticsearch
        tier: app
        role: master
    spec:
      serviceAccountName: {{.Release.Namespace}}-sa
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: elasticsearch
      - name: fluentd-config
        configMap:
          name: elasticsearch-fluentd-config
      containers:
      - name: elasticsearch
        image: {{required "Image Info is mandatory! Read the Project Documentation to understand what and where to configure." .Values.image.ELASTICSEARCH }}
        imagePullPolicy: IfNotPresent
        env:
        - name: ES_JAVA_OPTS
          {{- if (eq "Small" .Values.resourceUnit.size) }}
          value: -Xms512m -Xmx{{ .Values.resourceUnit.small.memory.max.ELASTICSEARCH }}m
          {{- else if (eq "Medium" .Values.resourceUnit.size) }}
          value: -Xms512m -Xmx{{ .Values.resourceUnit.medium.memory.max.ELASTICSEARCH }}m
          {{- else if (eq "Large" .Values.resourceUnit.size) }}
          value: -Xms512m -Xmx{{ .Values.resourceUnit.large.memory.max.ELASTICSEARCH }}m
          {{- else if (eq "Xlarge" .Values.resourceUnit.size) }}
          value: -Xms512m -Xmx{{ .Values.resourceUnit.xlarge.memory.max.ELASTICSEARCH }}m
          {{- end }}
        - name: processors
          value: "1"
        resources:
          limits:
            {{- if (eq "Small" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.small.memory.max.ELASTICSEARCH }}Mi
            cpu: {{ .Values.resourceUnit.small.cpu.max.ELASTICSEARCH }}m
            {{- else if (eq "Medium" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.medium.memory.max.ELASTICSEARCH }}Mi
            cpu: {{ .Values.resourceUnit.medium.cpu.max.ELASTICSEARCH }}m
            {{- else if (eq "Large" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.large.memory.max.ELASTICSEARCH }}Mi
            cpu: {{ .Values.resourceUnit.large.cpu.max.ELASTICSEARCH }}m
            {{- else if (eq "Xlarge" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.xlarge.memory.max.ELASTICSEARCH }}Mi
            cpu: {{ .Values.resourceUnit.xlarge.cpu.max.ELASTICSEARCH }}m
            {{- end }}
          requests:
            {{- if (eq "Small" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.small.memory.max.ELASTICSEARCH }}Mi
            cpu: {{ .Values.resourceUnit.small.cpu.max.ELASTICSEARCH }}m
            {{- else if (eq "Medium" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.medium.memory.max.ELASTICSEARCH }}Mi
            cpu: {{ .Values.resourceUnit.medium.cpu.max.ELASTICSEARCH }}m
            {{- else if (eq "Large" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.large.memory.max.ELASTICSEARCH }}Mi
            cpu: {{ .Values.resourceUnit.large.cpu.max.ELASTICSEARCH }}m
            {{- else if (eq "Xlarge" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.xlarge.memory.max.ELASTICSEARCH }}Mi
            cpu: {{ .Values.resourceUnit.xlarge.cpu.max.ELASTICSEARCH }}m
            {{- end }}
        volumeMounts:
        - mountPath: /data/elasticsearch
          name: data
          subPath: elasticsearch
        - mountPath: /usr/share/elasticsearch/data
          name: data
          subPath: data
        - mountPath: /usr/share/elasticsearch/config/logging.yml
          name: data
          subPath: conf/logging.yml
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          name: data
          subPath: conf/elasticsearch.yml
        - mountPath: /usr/share/elasticsearch/logs
          name: data
          subPath: logs
        - mountPath: /tmp
          name: data
          subPath: tmp
        securityContext:
          readOnlyRootFilesystem: true
        ports:
        - name: elasticsearch
          containerPort: 9300
      - name: fluentd
        image: {{ .Values.image.LOGZIO }}
        env:
        - name:  LOGZIO_TOKEN
          value: {{ .Values.logzio.token | quote }}
        - name:  LOGZIO_URL
          value: {{ .Values.logzio.url | quote }}
        - name: CONTAINER_NAME
          value: elasticsearch
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          value: elasticsearch
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            memory: {{ .Values.logzio.memory }}Mi
          requests:
            cpu: {{ .Values.logzio.cpu }}m
            memory: {{ .Values.logzio.memory }}Mi
        volumeMounts:
        - name: fluentd-config
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        - name: data
          mountPath: /usr/share/elasticsearch/logs
          subPath: logs
      imagePullSecrets:
      - name: container-registry-key
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        fsGroup: 1000
      allowedCapabilities: null

      
