apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 0
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongo
      labels:
        app: mongo
        tier: persistent-tier
        container_name: mongo
        environment: {{ .Values.label.ENVIRONMENT }}
    spec:
      serviceAccountName: security-service-account
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mongo
      - name: fluentd-config
        configMap:
          name: mongo-fluentd-config
      containers:
      - name: mongo
        image: {{required "Image Info is mandatory! Read the Project Documentation to understand what and where to configure." .Values.image.MONGO }}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            {{- if (eq "Small" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.small.memory.max.MONGO }}Mi
            cpu: {{ .Values.resourceUnit.small.cpu.max.MONGO }}m
            {{- else if (eq "Medium" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.medium.memory.max.MONGO }}Mi
            cpu: {{ .Values.resourceUnit.medium.cpu.max.MONGO }}m
            {{- else if (eq "Large" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.large.memory.max.MONGO }}Mi
            cpu: {{ .Values.resourceUnit.large.cpu.max.MONGO }}m
            {{- else if (eq "Xlarge" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.xlarge.memory.max.MONGO }}Mi
            cpu: {{ .Values.resourceUnit.xlarge.cpu.max.MONGO }}m
            {{- end }}
          requests:
            {{- if (eq "Small" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.small.memory.max.MONGO }}Mi
            cpu: {{ .Values.resourceUnit.small.cpu.max.MONGO }}m
            {{- else if (eq "Medium" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.medium.memory.max.MONGO }}Mi
            cpu: {{ .Values.resourceUnit.medium.cpu.max.MONGO }}m
            {{- else if (eq "Large" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.large.memory.max.MONGO }}Mi
            cpu: {{ .Values.resourceUnit.large.cpu.max.MONGO }}m
            {{- else if (eq "Xlarge" .Values.resourceUnit.size) }}
            memory: {{ .Values.resourceUnit.xlarge.memory.max.MONGO }}Mi
            cpu: {{ .Values.resourceUnit.xlarge.cpu.max.MONGO }}m
            {{- end }}
        volumeMounts:
        - mountPath: /data/db
          name: data
          subPath: db
        - mountPath: /tmp
          name: data
          subPath: tmp
        - mountPath: /var/log/mongodb
          name: data
          subPath: mongodb
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        ports:
        - name: mongo
          containerPort: 27017
      - name: fluentd
        image: {{ .Values.image.LOGZIO }}
        env:
        - name:  LOGZIO_TOKEN
          value: {{ .Values.logzio.token | quote }}
        - name:  LOGZIO_URL
          value: {{ .Values.logzio.url | quote }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: POD_UNIQUE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: CONTAINER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['container_name']
        - name: ENVIRONMENT
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['environment']
        - name: APP_TIER
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tier']
        resources:
          limits:
            memory: {{ .Values.logzio.memory }}Mi
          requests:
            cpu: {{ .Values.logzio.cpu }}m
            memory: {{ .Values.logzio.memory }}Mi
        volumeMounts:
        - name: fluentd-config
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        - name: data
          mountPath: /var/log/mongodb
          subPath: mongodb
      imagePullSecrets:
      - name: container-registry-key
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        fsGroup: 1000
      allowedCapabilities: null
