apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Release.Namespace}}-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{.Release.Namespace}}-cr
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resourceNames:
  - ms-unrestricted-psp
  resources:
  - pods
  - namespaces
  - podsecuritypolicies
  verbs:
  - get
  - list
  - watch
  - use
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{.Release.Namespace}}-crb
roleRef:
  kind: ClusterRole
  name: {{.Release.Namespace}}-cr
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{.Release.Namespace}}-sa
  namespace: {{ .Release.Namespace }}
